# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dxup < Formula
  desc "Reproducible development environments with Docker and Nix"
  homepage "https://github.com/dxupsh/dxup"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dxupsh/dxup/releases/download/v0.17.0/dxup_Darwin_x86_64.tar.gz"
      sha256 "8b9dc54a0af65918f5bb6d3c0103d7061e840631d0c77cbeb358d96db328dafa"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dxupsh/dxup/releases/download/v0.17.0/dxup_Darwin_arm64.tar.gz"
      sha256 "97a1aa6444013234c81102c5c2811aafba8676645324aa3e0a0a25598743bf2d"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.17.0/dxup_Linux_x86_64.tar.gz"
      sha256 "e16f2074724e8c469c31d0d7188844368107f5c8efd12c725008d2bf6ad37ccb"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.17.0/dxup_Linux_arm64.tar.gz"
      sha256 "702e03e77cadb5ec97a4645b526d8de45e0a033a25cd0f259138a1525e2023fc"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/dxup", "version"
  end
end
