# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dxup < Formula
  desc "Reproducible development environments with Docker and Nix"
  homepage "https://github.com/dxupsh/dxup"
  version "0.18.0"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Darwin_x86_64.tar.gz"
      sha256 "c711e0f5712ae9ed931cf385221489f8322863203ecca56002548e48203002fe"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Darwin_arm64.tar.gz"
      sha256 "7392dd5d48b13896a16a692077640c4bcf1bb7bd4a8abdbbbb2e20f97dacc5a2"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Linux_x86_64.tar.gz"
      sha256 "b36a67e43cd5a1fbdb30425d7940ecb900f6e40261ce4474114f8f34c0cd3c31"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.18.0/dxup_Linux_arm64.tar.gz"
      sha256 "0a5fae564f15d3e868ef3102946f440660f3d7bbf96e20ecc46328426245f9e0"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      dxup requires a Docker daemon. On macOS, we recommend Colima:
        brew install colima

      If you already use Docker Desktop or OrbStack:
        dxup setup --url unix:///var/run/docker.sock
    EOS
  end

  test do
    system "#{bin}/dxup", "version"
  end
end
