# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dxup < Formula
  desc "Reproducible development environments with Docker and Nix"
  homepage "https://github.com/dxupsh/dxup"
  version "0.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dxupsh/dxup/releases/download/v0.16.0/dxup_Darwin_x86_64.tar.gz"
      sha256 "816c8df9c40a4580f9f56cfe1c127f3096986268b2736917a8e75598a5c35cfe"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dxupsh/dxup/releases/download/v0.16.0/dxup_Darwin_arm64.tar.gz"
      sha256 "4ca4e49bc4a8838025e3c20c5e2917e59ae19866298415f72e44698301cbe8c0"

      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.16.0/dxup_Linux_x86_64.tar.gz"
      sha256 "5f5a7699d303ebcdb974af45a9d98d9c45b3aff4e2b8e325fd656f5d336441b5"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dxupsh/dxup/releases/download/v0.16.0/dxup_Linux_arm64.tar.gz"
      sha256 "e8ff021b252f8842945fb4fe0b781a94ff5fe79efc3176c793782a67dc628795"
      def install
        bin.install "dxup"
        bash_completion.install "docs/completions/dxup.bash" => "dxup"
        zsh_completion.install "docs/completions/_dxup"
        fish_completion.install "docs/completions/dxup.fish"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  test do
    system "#{bin}/dxup", "version"
  end
end
